### ISSUE TITLE
Auto rebuild when changing partials

### ISSUE THREAD

**Issue by johanhatlehols** [zurb/panini#10]
Hi,

first of all thanks for the great work on the new Foundation for Sites. I am currently using the Gulp/build system in the advanced starter project. Am I hoping too much if I would like Gulp to automatically rebuild the HTML files and reload the browser when I change a partial?

I'm a rookie using Gulp. Sorry if this question is misplaced!

**Comment by gakimball** [comment]
A newer version of the template implements this. Check it out here: <https://github.com/zurb/foundation-zurb-template/tree/v6-launch>

There's a new task called `pages:reset` which reloads all layouts and partials. And the `watch` task at the bottom as a new addition to run this task when any layouts or partials change.

**Comment by johanhatlehols** [comment]
Great. Thanks!

**Comment by simonh1000** [comment]
Hi, have downloaded everything freshly today, and I'm also not getting updates when a partial changes. would love to be prpviding a PR but can't quite work out the issue yet

**Comment by gakimball** [comment]
@simonh1000 Going to take another look at this in the next week, as we've still had issues with it internally.

**Comment by simonh1000** [comment]
I've advanced a bit (but not totally reliable yet) by using 
```
gulp.task('pages', function() {
  panini.refresh();
  return gulp.src('src/pages/**/*.{html,hbs,handlebars}')
```
and 
```
  gulp.watch(['src/{layouts,partials}/*.html'], function() {
      sequence([
          'pages',
          'reload'
       ]);
  });
```

**Comment by jasonsan3** [comment]
@simonh1000 I have made these changes and tested it four times. It seems to work very well. Still not solving the browser reload before compiling issue, though. I will keep fiddling too. 

Would this mean that you would drop the 'pages:reset' task altogether?

**Comment by simonh1000** [comment]
yes, and not least because the `gulp.run` there attracts a deprecation warning when being run

**Comment by gakimball** [comment]
Alright, I think this is resolved once and for all: zurb/foundation-zurb-template@d03994b77677c3548079736078e24ab796df57bd

To get these fixes, you only need to cut and paste the contents of `gulpfile.js`—no changes were made to dependencies.

Every task's stream now has a `finish` event listener that calls `browser.reload()`. So when the stream runs out of files to process, BrowserSync refreshes. This prevents the race condition resulting from Gulp trying to run a task and BrowserSync refreshing at the same time—in some cases, BrowserSync refreshes before the updated files are compiled, so you don't see the change.

There was also an issue with layouts, partials, etc. not updating when changed, or in some cases only updating once. This happened because the `pages:reset` task was not finishing properly. This means Gulp won't run it a second time. I also added `data` and `helpers` to the list of watched folders, so those will update as well.

The use of `gulp.run()` is still in there, so you're going to get a deprecation warning. There's just not a better way to resolve this within Gulp 3's paradigms. We're working on a Gulp 4 version of the template (see zurb/foundation-zurb-template#28) that more elegantly solves these problems.

**Comment by Snigros** [comment]
Thanks to everyone involved for fixing this so quickly (I thought I was going mad at first).

**Comment by johanhatlehols** [comment]
Lots of action. Amazing community! Thanks to all of you :)

**Comment by TimLavelle** [comment]
Thanks for the quick update!

**Comment by amit-gshe** [comment]
This issue seems appears again with the latest nodejs or the foundation-sites template. The panini can works fine when I first saving a file but then it doesn't rebuild partitials anymore and I have to restart whith `npm start`. Does any one encounter this problem?

**Comment by jeckojim** [comment]
Yep, same here fresh install from yesterday...

**Comment by jeckojim** [comment]
@amit-gshe For me it was related to the gulpfile with the Zurb template of Foundation, see [here](https://github.com/zurb/foundation-zurb-template/pull/37) the issue, and the [code](https://raw.githubusercontent.com/phated/foundation-zurb-template/fix-reload/gulpfile.babel.js) that fixed it for me.

**Comment by amit-gshe** [comment]
@jeckojim  You saved my time. Thanks!

**Comment by tobystokes** [comment]
I know this issue is specifically partials, but should the same refresh() method apply to helpers and data too?
I notice in the latest gulpfile template, they are not included in the watch task.
Currently though, expanding that to e.g 
```gulp.watch('src/{layouts,partials,helpers,data}/**/*', gulp.series(resetPages, pages, browser.reload));
appears to trigger 'resetPages', but is still using cached data/*
