### ISSUE TITLE
Compatible with webpack?

### ISSUE THREAD

**Issue by kee0624** [zurb/panini#120]
I feel this features is very good, so I am thinking are you plan to make this compatible with webpack?

**Comment by gakimball** [comment]
Are you trying to use Panini in the browser?

And either way, can you paste any errors you got when you write `import panini from 'panini';`?

**Comment by kee0624** [comment]
I am using panini for generate dynamic html file for my gulp project. Which for multipage html development instead of app development. but currently approach for htmlwebpack plugin is not working for dynamic filename.
which I can't do like 

new HtmlWebpackPlugin({
      template: 'src/layouts/index.ejs',
      filename: '[name].html',
 }),

so want to know do you have any plan for this in the future?

**Comment by gakimball** [comment]
We don't have any plans for implementing any Webpack loader versions of template engines into Panini. This library is mostly for using Handlebars, EJS, Pug, etc. as-is.

I don't think you'll have much success mixing Panini and Webpack to make a static site, because both libraries are doing the same thing: they're taking template files and compiling them into finished HTML. They can't really share the compiling process.

However, if you could explain to me further what you're trying to do, that would be super helpful :)

**Comment by york-xtrem** [comment]
The only thing I do not totally change to webpack is by Panini. I think the work you've done with Panini is exceptional and saves me a lot of setup time.
If somehow I could integrate it with Webpack would be great!

Not a big problem but I have three bundles:

- Core: frameworks and libraries.
   - Concatenated file -> core.js
- Common: javascript files that are shared between different pages.
   - Concatenated file -> common.js
- Main: javascript files that are on each page.
   - Concatenated file -> main.js

With gulp-rev-replace when in production I concatenated them in a single bundle. Now all that work of injecting <script src = ""> </ script> is done by HtmlWebpackPlugin. So I do not use Gulp and if I had a solution to use Panini it would be wonderful!

**Comment by kuzvac** [comment]
Hi @gakimball, thank you for your amazing work on panini, buuut maybe in v2.0 you made loader for webpack, or piece of code, how to integrate into HtmlWebpackPlugin? :)

**Comment by york-xtrem** [comment]
@kuzvac You read about nunjucks and enjoy! ;)
