### ISSUE TITLE
What's the equivalent of panini.refresh() in v2.0?

### ISSUE THREAD

**Issue by lipis** [zurb/panini#151]
So I'm using the version 2.0 for the foundation emails (because folders in partials). Everything works nicely except the [`panini.refresh()`](https://github.com/zurb/foundation-emails-template/blob/master/gulpfile.babel.js#L67).. What can I do to have the automatic refreshes without restarting the build process?

**Comment by gakimball** [comment]
The API is sort of half-finished right now, so refreshing isn't super easy unfortunately. My intent is to get rid of that function and have internal watchers for pages/partials/layouts/helpers/data that restart the build process for you. I've had a few false starts in trying to implement it.

There's a temporary solution in #143. The `refresh()` function is still in there, it's just a little tricky to get to.

I'm using Panini 2 with Foundation for Emails myself, although with the CLI. And I am having to get around the not-easy-refresh issue by just re-running the whole process every time a file changes. It's annoying, but thankfully the project is small enough that I don't notice the compile times.

Since this is similar to #143, I'm going to close this. Thank you for bearing with me, and I appreciate you helping me test out this almost-finished-but-not-quite update! :)
