### ISSUE TITLE
How can I get an array of all the 'pages' to use in navigation topbar?

### ISSUE THREAD

**Issue by simonh1000** [zurb/panini#23]

**Comment by gakimball** [comment]
It's not currently possible to do this in Panini, because of how Gulp works. The plugin parses each page in isolation, so individual pages aren't aware of each other.

We can look at this feature further down the road, but it likely won't happen in the near future due to the internal changes needed.

**Comment by simonh1000** [comment]
OK, I can get quite a long way with a json data file
