### ISSUE TITLE
Handlebars file format should not be .html by default

### ISSUE THREAD

**Issue by Abhra1992** [zurb/panini#3]
Handlebars files should generally have `.hbs` as a file extension. Using `.html` as default might cause problems in piping from/to other gulp plugins.

**Comment by lyckron** [comment]
+1 for .hbs extension.

**Comment by lyckron** [comment]
Just began working on a feature branch that supports `.hbs` and `.handlebars` extension for layouts, pages and partials.

I'm thinking of adding an optional `templateExt` property to the `settings` object, so the gulp task would look like this:

```javascript
gulp.task('default', function() {
  gulp.src('pages/**/*')
    .pipe(panini({
      layouts: 'layouts/',
      partials: 'partials/**/*',
      data: 'data/**/*.{json,yml}',
      helpers: 'helpers/**/*.js',
      templateExt: '.hbs' // could also be '.handlebars'
    }))
    .pipe(gulp.dest('_build'));
});
```
This way the target templates will be isolated to the extension given in `templateExt`, and will reduce the overhead, of having to evaluate and process different file extensions in the module logic.

Obviously, this means that people won't be able to mix the extensions, maybe something like this:

```javascript
gulp.task('default', function() {
  gulp.src('pages/**/*.html')
    .pipe(panini({
      layouts: 'layouts/*.hbs',
      partials: 'partials/**/*.hbs',
      data: 'data/**/*.{json,yml}',
      helpers: 'helpers/**/*.js'
    }))
    .pipe(gulp.dest('_build'));
});
```
But really, if some would like to reuse their old `.html` templates - all they would have to do, is renaming them to `.hbs` or `.handlebars`.

So, if the `templateExt` property is **NOT** included in the `settings` object, then `.html` extension will still be the default.

Any objections?

**Comment by Abhra1992** [comment]
I believe that will be a good addition to the plugin. `.hbs` and `.handlebars` extensions will also help facilitate editor syntax highlight support.

**Comment by gakimball** [comment]
@lyckron I wonder if it's easier for developers if you just specify a directory for each kind of content instead of a glob pattern. That's less flexible perhaps, but also easier to read, and I'm okay with keeping the file structure strict (i.e. all layouts must be in the same folder).

From there you hardcode the kinds of file extensions you're looking for:
- `.html`, `.hbs`, and `.handlebars` for layouts, pages, and partials
- `.js` for helpers
- `.yml` and `.json` for data

**Comment by lyckron** [comment]
I agree, the [approach](https://github.com/lyckron/panini/tree/draft/handlebars-extension-and-test) I've managed based on the master as it is seems a bit hack'y because of the gulp stream. 

Dropped the `templateExt` btw, it didn’t make sense, since I'd had to process file endings from the `pages` stream anyway.  

I like the idea of #6, taking control of the `src` and `dest` in the module would also make the logic much easier to work with.

But let me know if we should use this approach until the re-factoring, and I'll sync with upstream and send you a PR.

Using this approach though, you have to specify a glob for layouts!, ex. like `layouts: 'layouts/*.hbs'`

**Comment by gakimball** [comment]
I can definitely merge in what you have, but I need to get this thing done in the next week, so I'm going to start on the refactoring real soon.

**Comment by gakimball** [comment]
Also worth noting that the directory-based approach makes handling relative paths easier. I need to add a `root` Handlebars variable that can detect if a page is in a subdirectory, so you can do relative paths to assets, like so:

```html
<link rel="stylesheet" href="{{root}}assets/css/app.css">
```

It prints an empty string for a root-level page, and `../` for a page in a subdirectory.

**Comment by lyckron** [comment]
Yeah was working on a boilerplate project, and something like the `root` helper was actually the reason for my first PR regarding `registerHelper`.

Was thinking of using [app-root-path](https://www.npmjs.com/package/app-root-path) and [path.relative](https://nodejs.org/api/path.html#path_path_relative_from_to) for that one.

All right, with that short deadline, my branch won't be of much use :) 

Nevertheless, I've sent you a PR you can use as backup if the 1.0 for some reason should be delayed.

**Comment by gakimball** [comment]
With the refactor, `.html`, `.hbs`, or `.handlebars` files can be used for layouts or partials. For the pages themselves, you can use anything because they come from `gulp.src`.

e8a8b878edb91b2441a6881a6f7b1215234f2a6b
f87b82c1ea3cf6db1580a5742a8dc4c5c99831d6
