### ISSUE TITLE
json initial build only

### ISSUE THREAD

**Issue by jamesPrecedent** [zurb/panini#37]
I am trying to generate at TOC for my project and have all pages being listing in a json file (using gulp-directory-map).
However this TOC only generates on the initial build. If I add pages into the project - the json file updates but the TOC index page doesn't update after browser refresh.
I have simulated this with a static json file and the same problem happens.
I have also tried this using a yml data source and this does actually update on the TOC page.
URL for example repo - any help would be amazing!
http://templates.precedenthost.co.uk/panini/panini-build.zip

**Comment by gakimball** [comment]
Panini caches the layouts, partials, helpers, and data you give it, to speed up incremental builds. To get around this, it has a `.refresh()` method you can run to re-load everything.

When a page changes, you need to:

- Re-run your directory index task
- Run `panini.refresh()` when that finishes
- Run your `pages` task

The order is important. If one page changes, you can't just compile that one page and be done, because the content of *every* page is now affected.

The above process means that when a page changes, you create a new directory, which is then loaded into Panini, *before* all of the pages run through Panini again.

For a 2.0 of this library we're looking to add more hooks that make Panini itself aware of your site structure. Right now, since every page is processed in a vacuum, there's no way to get data like that.

Let me know if the above solution helps! :)
