### ISSUE TITLE
Mocha unit test for expected build output.

### ISSUE THREAD

**Issue by lyckron** [zurb/panini#4]
Working on the handlebars extension branch, I realized that an automated unit test for the expected build output would be nice.

Actually, I just finished a branch that does this for the master branch as it is now. 

@gakimball, I would love to know what you Zurb guys think of my implementation proposal for issue #3.

Because if it's a go, then I'll pull the testing branch into the extension branch, and send it as a single PR.

The beta for zf6 looks great btw. :)

**Comment by gakimball** [comment]
Yes, I'd like a test suite for this thing eventually. The first step there would probably be breaking up that big `index.js` file into smaller, more easily testable pieces.

**Comment by gakimball** [comment]
Related: #6

**Comment by lyckron** [comment]
Yup, re-factoring as mentioned in #6  and breaking up the `index.js` would make actual unit testing possible.. I like that idea.

[The test](https://github.com/lyckron/panini/tree/feature/mocha-testing) approach I've use only test if the whole module through gulp tasks is able to output the expected result.

This test approach could be used though, until the re-factoring of #6 is finished?

Let my know, and sync with upstream and send you a PR.

btw, I also pulled it in my [handlebars extension draft](https://github.com/lyckron/panini/tree/draft/handlebars-extension-and-test), but we should properly discuss that branch in #3.

**Comment by gakimball** [comment]
The refactor didn't take nearly as long as I thought, and I'm pretty happy with the result. Like you said, though, it's still maybe kinda awkward to test because you have to use it in a Gulp context to test the expected output.

I like your approach of having a precise expected output folder, though. I'm guessing you could test some of the individual functional areas by verifying that the internal Handlebars instance updated properly? And then you can also test the Gulp stream function and see if all of the pieces actually come together. The test files I have right now are really messy and need some organization. These are the functional areas that need testing:

(This is a big ask, but if you're interested in helping, the Foundation team will love you forever :) I can also hook you up with hot swag.)

- Pages render with the default layout.
- Pages render with a different layout if configured in Front Matter.
- Page data in Front Matter is available as Handlebars variables.
- Partials configured in plugin settings are available as Handlebars partials.
- Helpers configured in plugin settings are available as Handlebars helpers.
- Data files configured in plugin settings are available as Handlebars variables.
- Built-in variables:
  - `page` is the filename of the current page without its extension.
  - `root` is an empty string for root-level pages, or `../` for pages inside a subdirectory.
- Built-in helpers:
  - `#ifpage` renders content if a page matches.
  - `#unlesspage` renders content unless a page matches.
  - `#repeat` repeats content n times.
  - `#markdown` converts Markdown to HTML.

**Comment by gakimball** [comment]
Currently in progress on the `tests` branch.

**Comment by gakimball** [comment]
Done!
