### ISSUE TITLE
Add png sprites with gulp.spritesmith

### ISSUE THREAD

**Issue by Adam16** [zurb/panini#53]
I needed Sprites Images. I installed this about that:

`npm install ulp.spritesmith`

Installed version ^6.2.1

For that I have extended this file: ./template/gulpfile.babel.js

Import library:
`import spritesmith from 'gulp.spritesmith';`

Conversion function:
`
function sprite() {
    var spriteSmith = gulp.src('src/assets/sprites/_')
        .pipe(spritesmith({
            retinaSrcFilter: 'src/assets/sprites/_@2x.png',
            retinaImgName: '../img/sprite@2x.png',
            imgName: '../img/sprite.png',
            cssName: '_sprite.scss',
            algorithm: 'binary-tree'
        }));

```
spriteSmith.img.pipe(gulp.dest('src/assets/img'));
spriteSmith.css.pipe(gulp.dest('src/assets/scss/components'));

return spriteSmith;
```

}
`
And watch:
`gulp.watch('src/assets/sprites/*_/_.png', gulp.series(sprite, browser.reload));`

Import all generated mixin in app.css
`@import 'components/sprite';`

It works in my case. That as an idea

**Comment by gakimball** [comment]
Hey! This issue is very old, but this specific feature is outside the scope of Panini, which just handles HTML.

If you have suggestions or issues with the ZURB Template, which uses Panini (and also handles Sass, JavaScript, images, etc.), you can open an issue on the [Foundation for Sites](https://github.com/zurb/foundation-sites/issues) repo.
