### ISSUE TITLE
Would like to use helpers in Front Matter variables

### ISSUE THREAD

**Issue by chrisbloom7** [zurb/panini#66]
Given the following setup:

```
helpers
  primary.js
pages
  index.html
partials
  heading.html
```

When index.html contains:

```

---
heading: You got {{#primary}}200{{/primary}} points!

---
{{> heading}}
<row>
  <columns small="12" large="12">
    <p>{{#primary}}Well done!{{/primary}}</p>
  </columns>
</row>
```

And heading.html contains:

```
<row>
  <columns small="12" large="12">
    <h1>
      {{ heading }}
    </h1>
  </columns>
</row>
```

Then the helper isn't being applied and I end up with `You got {{#primary}}200{{/primary}} points!` in that section, though it does properly apply the helper to the next section.

**Comment by gakimball** [comment]
Not possible, unfortunately.

The Front Matter is static metadata. When Panini renders a page, it pulls the Front Matter out of the original page, and converts it into a data object. That data object is then accessible in Handlebars, like so:

```handlebars
---
name: Chris
---

<p>Hi, {{ name }}</p>
```

The Front Matter has to be parsed and removed *before* Handlebars can do its thing—otherwise you've created a circular dependency.

I'm not sure what your `{{#primary}}` helper does, but if it's just a formatting thing (like adding HTML around the contents), there are ways to do that without having dynamic Front Matter.

It's best to think of the Front Matter as pure data, and not having anything to do with presentation.
