### ISSUE TITLE
Output for Mandrill HBS

### ISSUE THREAD

**Issue by rickysullivan** [zurb/panini#90]
Our company uses Mandrill for sending out transaction emails. I'm using their Handlebars tempting language for sending out emails via their API.

I wanted to use panini for its partials support so I can build multiple transactional emails. But I don't want to render standard Handlebars `{{variable}}` or `{{#if variable}}...{{/if}}`. Is there a way I can prevent panini from doing this?

**Comment by gakimball** [comment]
This is tricky because, although you can [escape Handlebars expressions](http://handlebarsjs.com/expressions.html), if you do that, they'll *also* be escaped by Mandrill's Handlebars parser presumably.

In that case, your only option would be to mix templating languages. Panini doesn't support anything other than Handlebars, but it might soon—see #16.

Then you could, for example, write templates in Pug, and keep your Handlebars code for Mandrill.

```pug
h1 Hello, {{ name }}
```

I know this is an old issue, but if you have any other questions let me know :)

**Comment by gakimball** [comment]
Okay, well, after a good night's sleep, I realize I was *definitely wrong*. Escaping Handlebars expressions in Panini will work fine—the code will then be preserved for Mandrill. See the link in the above comment for the docs on escaping Handlebars.

**Comment by rickysullivan** [comment]
Hi there. I ended up using our own partial system. But then still needed to escape my handlebars code.

This is what I used:

```
    var inkyopts = {
      cheerio: {
        xmlMode: false,
        decodeEntities: false,
        applyAttributesTableElements: false,
        applyWidthAttributes: true
      }
    }

    html = html.replace(/(\{\{(?:#if|#unless|elseif)[^}]+\}\})/g, '<!--[CDATA[$1]]-->');

    var i = new inky.Inky(inkyopts);

    var inkyhtml = cheerio.load(html, opts.cheerio);

    html = i.releaseTheKraken(inkyhtml, opts.cheerio);

    //  Inline CSS
    html = juice(html, inkyopts.cheerio);

    html = html.replace(/<!--\[CDATA\[(.*?)\]\]-->/g, '$1');

```
